name: Testing

on:
  push:
    branches:
    - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Setup env
      run: |
        pip install pyenv
        make venv
    - name: Run tests
      run: make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
