name: Testing

on:
  push:
    branches:
    - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: "3.9"
    steps:
    - uses: actions/checkout@main
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Setup env
      run: |
        pip install pipenv
        make venv
    - name: Run tests
      run: make test
    - name: Upload coverage to Coverall
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
